<a href="https://colab.research.google.com/github/Etor-git/ciencia_de_datos/blob/main/Pandas_df2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1:

In [ ]:
import pandas as pd

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
df = pd.read_csv("Cleaned_HR_Data_Analysis.csv")

In [4]:
empleados_ma = df[(df["EmployeeStatus"] == "Active") & (df["State"] == "MA")]
empleados_ma.head()

,Employee ID,StartDate,Title,BusinessUnit,EmployeeStatus,EmployeeType,PayZone,EmployeeClassificationType,DepartmentType,Division,...,Engagement Score,Satisfaction Score,Work-Life Balance Score,Training Date,Training Program Name,Training Type,Training Outcome,Training Duration(Days),Training Cost,Age
0,3427,20-Sep-19,Production Technician I,CCDR,Active,Contract,Zone C,Temporary,Production,Finance & Accounting,...,1,2,3,15-Jul-23,Leadership Development,Internal,Failed,2,606.11,50
1,3428,11-Feb-23,Production Technician I,EW,Active,Contract,Zone A,Part-Time,Production,Aerial,...,2,1,5,12-Sep-22,Customer Service,External,Incomplete,4,673.02,58
2,3429,10-Dec-18,Area Sales Manager,PL,Active,Full-Time,Zone B,Part-Time,Sales,General - Sga,...,1,2,1,13-Aug-22,Leadership Development,External,Failed,2,413.28,27
15,3442,09-Jul-19,Area Sales Manager,PYZ,Active,Full-Time,Zone A,Full-Time,IT/IS,Field Operations,...,2,5,3,06-Mar-23,Project Management,External,Failed,4,286.87,67
23,3453,13-Oct-22,Area Sales Manager,WBL,Active,Contract,Zone C,Part-Time,Sales,Fielders,...,5,5,3,25-Aug-22,Customer Service,External,Completed,5,964.44,40

In [5]:
df.shape

(2845, 28)

In [6]:
resultado = empleados_ma[["Employee ID", "Title", "Performance Score"]]
print(resultado.head())

    Employee ID                    Title Performance Score
0          3427  Production Technician I       Fully Meets
1          3428  Production Technician I       Fully Meets
2          3429       Area Sales Manager       Fully Meets
15         3442       Area Sales Manager           Exceeds
23         3453       Area Sales Manager       Fully Meets

In [7]:
resultado.shape

(2152, 3)

**Ejercicio 2**
Agrupación y Estadística Descriptivas
**Objetivo:** Aplicar la metodología split-apply-combine para resumir datos numéricos por categorías.
Calcula el promedio del "Engagement Score", "Satisfaction Score", y "Work-Life Balance Score" para cada unidad.
Ordena los resultados de mayor a menor basándote en el "Engagement Score" para identificar la unidad con empleados más comprometidos.

In [10]:
metricas_unidad = df.groupby("BusinessUnit")[["Engagement Score", "Satisfaction Score", "Work-Life Balance Score"]].mean()

In [11]:
ranking_compromiso = metricas_unidad.sort_values(by="Engagement Score", ascending=False)
#print(ranking_compromiso)
ranking_compromiso

              Engagement Score  Satisfaction Score  Work-Life Balance Score
BusinessUnit
PYZ                   3.056140            3.129825                 3.024561
MSC                   2.992908            2.985816                 3.049645
NEL                   2.989691            3.075601                 2.920962
WBL                   2.982517            2.982517                 3.031469
TNS                   2.957597            2.954064                 2.908127
SVG                   2.943060            2.943060                 3.049822
BPC                   2.909722            3.062500                 2.840278
CCDR                  2.876761            3.091549                 2.883803
EW                    2.854610            3.131206                 3.170213
PL                    2.851590            2.925795                 3.017668

Ejercicio 3:
Tablas Dinámicas y Análisis de Costos de Capacitación
Objetivo: Utilizar pivot_table para analizar

In [12]:
tabla_costos = df.pivot_table(values="Training Cost", index= "DepartmentType", columns="Training Outcome", aggfunc="sum", margins=True)

In [13]:
#print(tabla_costos)
tabla_costos

Training Outcome      Completed     Failed  Incomplete     Passed         All
DepartmentType
Admin Offices          12386.69    9066.96    10842.90    9803.97    42100.52
Executive Office        2682.54    4500.07     2766.94    4101.72    14051.27
IT/IS                  63724.31   64066.44    45045.05   57560.54   230396.34
Production            267534.62  242887.21   283166.27  276678.05  1070266.15
Sales                  49454.38   33487.14    46918.21   38157.25   168016.98
Software Engineering   20645.08   18149.50    15412.97   12109.82    66317.37
All                   416427.62  372157.32   404152.34  398411.35  1591148.63